"""empty message

Revision ID: cf932aebc4f5
Revises: 
Create Date: 2021-04-26 21:03:52.979056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf932aebc4f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['Status'], ['id'])

    # ### end Alembic commands ###
